Update RunTest.yml

diff --git a/.github/workflows/RunTest.yml b/.github/workflows/RunTest.yml
--- a/.github/workflows/RunTest.yml
+++ b/.github/workflows/RunTest.yml
@@ -1,36 +1,46 @@
-# This is a basic workflow to help you get started with Actions
+name: Manual StartUT
 
-name: CI
-
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
+on: 
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+  Test:
+    runs-on: [self-hosted, windows]
+    timeout-minutes: 90
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      # check out branch
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+          token: ${{secrets.GITHUB_TOKEN}}
+#         token: ${{secrets.PERSONAL_ACCESS_TOKEN}} 
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      # show path
+      - name: Show current directory
+        run: dir
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+      # Run the unit test
+      - name: Run MATLAB Unit Tests
+        uses: matlab-actions/run-command@v1
+        with:
+          command: addpath(genpath(pwd)),addpath('Script'),RunUnitTestsParallel
+
+      - name: Remove Task from Queue
+        if: always()
+        uses: matlab-actions/run-command@v1
+        with:
+          command: addpath('Script'),RemoveTaskFromQueue
+
+      - name: Upload Comparison Reports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+           name: UnitTest
+           path: ${{ github.workspace }}\Outputs\*.pdf
+           retention-days: 21
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: ${{ github.workspace }}\Outputs\*.xml
